In [27]:
#import libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as matplot
import seaborn as sns

# control display for seaborn data - optional
pd.options.display.max_columns=50
sns.set(style="darkgrid", rc={"axes.facecolor":"#CAF1DE"})

In [28]:
#Load the dataset
df4 = pd.read_csv('bse_dataset4.csv')
df4

,Timestamp,gender,Age,emotion,YOB,CGPA,Do you have a Girl Friend or BOY Friend,Do you have Depression?,Do you have Anxiety?,Do you have Panic attack?,Did you have seek any specialist for a treatment?,Duration,Pulse,Maxpulse,Calories
0,05/07/2023 09:38:39,Male,21.0,Content,2002,4.22,No,No,Yes,Yes,Yes,60,110,130,409.1
1,05/07/2023 09:38:57,Marabou stock,45.0,Weird,2100,8.9,Yes,Yes,Yes,Yes,No,60,117,145,479.0
2,05/07/2023 09:39:09,Female,20.0,Happy,2002,3.98,No,No,Yes,Yes,No,60,103,135,340.0
3,05/07/2023 09:39:12,Male,21.0,Happy,2003,4.37,No,No,No,No,Nope,45,109,175,282.4
4,05/07/2023 09:39:14,Female,21.0,Happy,2002,3.63,No,No,No,No,No,45,117,148,406.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
164,05/07/2023 09:44:09,Male,22.0,Angry,1999,3.5,Yes,No,No,No,No,60,105,140,290.8
165,05/07/2023 09:44:14,male,23.0,sad,1999,4,no,no,no,no,no,60,110,145,300.0
166,05/07/2023 09:44:15,male,20.0,calm,2002,3.7,yes,no,no,no,no,60,115,145,310.2
167,05/07/2023 09:44:35,Female,21.0,sad,2001,3.8,no,no,yes,no,no,75,120,150,320.4
168,05/07/2023 09:45:13,Female,20.0,Happy,2022,4......,no,no,no,yes,no,75,125,150,330.4

In [29]:
# Confirm data shape
df4.shape

(169, 15)

In [30]:
df4.columns

Index(['Timestamp', 'gender', 'Age', 'emotion', 'YOB', 'CGPA',
       'Do you have a Girl Friend or BOY Friend', 'Do you have Depression?',
       'Do you have Anxiety?', 'Do you have Panic attack?',
       'Did you have seek any specialist for a treatment? ', 'Duration',
       'Pulse', 'Maxpulse', 'Calories'],
      dtype='object')

In [31]:
df4_new = df4.dropna()
df4_new

,Timestamp,gender,Age,emotion,YOB,CGPA,Do you have a Girl Friend or BOY Friend,Do you have Depression?,Do you have Anxiety?,Do you have Panic attack?,Did you have seek any specialist for a treatment?,Duration,Pulse,Maxpulse,Calories
0,05/07/2023 09:38:39,Male,21.0,Content,2002,4.22,No,No,Yes,Yes,Yes,60,110,130,409.1
1,05/07/2023 09:38:57,Marabou stock,45.0,Weird,2100,8.9,Yes,Yes,Yes,Yes,No,60,117,145,479.0
2,05/07/2023 09:39:09,Female,20.0,Happy,2002,3.98,No,No,Yes,Yes,No,60,103,135,340.0
3,05/07/2023 09:39:12,Male,21.0,Happy,2003,4.37,No,No,No,No,Nope,45,109,175,282.4
4,05/07/2023 09:39:14,Female,21.0,Happy,2002,3.63,No,No,No,No,No,45,117,148,406.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
164,05/07/2023 09:44:09,Male,22.0,Angry,1999,3.5,Yes,No,No,No,No,60,105,140,290.8
165,05/07/2023 09:44:14,male,23.0,sad,1999,4,no,no,no,no,no,60,110,145,300.0
166,05/07/2023 09:44:15,male,20.0,calm,2002,3.7,yes,no,no,no,no,60,115,145,310.2
167,05/07/2023 09:44:35,Female,21.0,sad,2001,3.8,no,no,yes,no,no,75,120,150,320.4
168,05/07/2023 09:45:13,Female,20.0,Happy,2022,4......,no,no,no,yes,no,75,125,150,330.4

In [32]:
df4_new = df4.dropna(inplace=True)
df4

,Timestamp,gender,Age,emotion,YOB,CGPA,Do you have a Girl Friend or BOY Friend,Do you have Depression?,Do you have Anxiety?,Do you have Panic attack?,Did you have seek any specialist for a treatment?,Duration,Pulse,Maxpulse,Calories
0,05/07/2023 09:38:39,Male,21.0,Content,2002,4.22,No,No,Yes,Yes,Yes,60,110,130,409.1
1,05/07/2023 09:38:57,Marabou stock,45.0,Weird,2100,8.9,Yes,Yes,Yes,Yes,No,60,117,145,479.0
2,05/07/2023 09:39:09,Female,20.0,Happy,2002,3.98,No,No,Yes,Yes,No,60,103,135,340.0
3,05/07/2023 09:39:12,Male,21.0,Happy,2003,4.37,No,No,No,No,Nope,45,109,175,282.4
4,05/07/2023 09:39:14,Female,21.0,Happy,2002,3.63,No,No,No,No,No,45,117,148,406.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
164,05/07/2023 09:44:09,Male,22.0,Angry,1999,3.5,Yes,No,No,No,No,60,105,140,290.8
165,05/07/2023 09:44:14,male,23.0,sad,1999,4,no,no,no,no,no,60,110,145,300.0
166,05/07/2023 09:44:15,male,20.0,calm,2002,3.7,yes,no,no,no,no,60,115,145,310.2
167,05/07/2023 09:44:35,Female,21.0,sad,2001,3.8,no,no,yes,no,no,75,120,150,320.4
168,05/07/2023 09:45:13,Female,20.0,Happy,2022,4......,no,no,no,yes,no,75,125,150,330.4

In [33]:
df4 = df4.fillna(100, inplace=True)
df4
# inplace = TRUE means that the changes are saved to the data frame right away